#环境隔离，开发环境下的配置文件
sky:
  datasource:
    #驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接的url
    host: localhost
    port: 3306
    database: sky_take_out
    #连接数据库的用户名
    username: root
    #连接数据库的密码
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 10
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com #阿里云OSS-Bucket-概览-访问端口-Endpoint
    access-key-id: LTAI5tGFpKBCLiwBiz3ersp2 #旧版直接配置AccessKeyId
    access-key-secret: lZ7va5Fbtp7S1MLJWg2UcvEJv0wrop #旧版直接配置AccessKeySecret
    bucket-name: cmz-sky-take-out #阿里云OSS-Bucket-概览-基本信息-存储空间名称
  wechat:
    appid: wx560e0c39a9abbcd6 #微信小程序的APPID
    secret: 28aec77ee5313ccf4794f23ac4b31678 #微信小程序的密钥
    mchid: #微信商户号
    mch-serial-no: #微信商户API证书序列号
    private-key-file-path: #微信商户私钥文件路径
    api-v3-key: #微信商户API证书解密的密钥
    we-chat-pay-cert-file-path: #微信支付平台证书
    notify-url: #支付成功的回调地址
    refund-notify-url: #退款成功的回调地址
