server:
  port: 8080

spring:
  profiles:
    active: dev
#    active: prod
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name} #驱动类名称
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username} #连接数据库的用户名
    password: ${sky.datasource.password} #连接数据库的密码
  data:
    redis:
      host: ${sky.data.redis.host}
      port: ${sky.data.redis.port}
      password: ${sky.data.redis.password}
      database: ${sky.data.redis.database}

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.sky.controller
  group-configs:
    - group: 管理端接口
      paths-to-match:
        - /admin/**
      packages-to-scan:
        - com.sky.controller
    - group: 用户端接口
      paths-to-match:
        - /user/**
      packages-to-scan:
        - com.sky.controller
    - group: 外部回调接口
      paths-to-match:
        - /notify/**
      packages-to-scan:
        - com.sky.controller

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: skytakeout
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: skytakeoutuser
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置jwt签名加密时使用的秘钥
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint} #阿里云OSS-Bucket-概览-访问端口-Endpoint
    access-key-id: ${sky.alioss.access-key-id} #旧版直接配置AccessKeyId
    access-key-secret: ${sky.alioss.access-key-secret} #旧版直接配置AccessKeySecret
    bucket-name: ${sky.alioss.bucket-name} #阿里云OSS-Bucket-概览-基本信息-存储空间名称
  wechat:
    appid: ${sky.wechat.appid} #微信小程序的APPID
    secret: ${sky.wechat.secret} #微信小程序的密钥
    mchid: ${sky.wechat.mchid} #微信商户号
    mch-serial-no: ${sky.wechat.mch-serial-no} #微信商户API证书序列号
    private-key-file-path: ${sky.wechat.private-key-file-path} #微信商户私钥文件路径
    api-v3-key: ${sky.wechat.api-v3-key} #微信商户API证书解密的密钥
    we-chat-pay-cert-file-path: ${sky.wechat.we-chat-pay-cert-file-path} #微信支付平台证书
    notify-url: ${sky.wechat.notify-url} #支付成功的回调地址
    refund-notify-url: ${sky.wechat.refund-notify-url} #退款成功的回调地址
  baidu:
    ak: ${sky.baidu.ak} #百度地图API应用的AccessKey
