sky:
  datasource:
    #驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接的url
    host: localhost
    port: 3307
    database: sky_take_out
    #连接数据库的用户名
    username: root
    #连接数据库的密码
    password: 123456
